FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gcc \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*


RUN pip install --no-cache-dir psycopg2-binary pandas matplotlib
WORKDIR /app

COPY query_script.py /app/query_script.py
EXPOSE 5432

CMD ["sh", "-c", "python3 /app/query_script.py && tail -f /dev/null"]
