
FROM postgres:14-alpine

RUN apk add --no-cache bash icu-libs

ENV POSTGRES_DB=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

RUN mkdir -p /app

COPY ./DailyDelhiClimateTrain.csv /docker-entrypoint-initdb.d/DailyDelhiClimateTrain.csv
COPY ./init.sql /docker-entrypoint-initdb.d/init.sql

ENV LANG en_US.utf8
EXPOSE 5432
CMD ["postgres"]
